---
title: Pow Acad
timezone: UTC
collections:
  auteurs:
    title: Auteurs
    output: true
    permalink: "/auteurs/:path/"
  cours:
    title: Cours
    output: true
    permalink: "/cours/:path/"
  partenaires:
    title: Partenaires
    output: true
    permalink: "/partenaires/:path/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Parce qu'apprendre est un plaisir.
github_info:
  organization: MuBrain
  repository: 
  default_branch: master
anchor_js_targets:
- h1
- h2
- h3
- h4
- h5
- h6
sass:
  style: compressed
